version: 2

mkdocs: {}  # tell readthedocs to use mkdocs

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

formats:
  - pdf
  - epub

python:
  install:
  - method: pip
    path: .
  - requirements: docs/requirements.txt
  - requirements: requirements.txt  # so that mkapi can inspect the API
