version: '{build}'

image:
  - Ubuntu2204
  - macos

configuration: Release

platform:
  - x64

for:
-
  matrix:
    only:
      - image: macos
  install:
    - curl -Ls https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
    - mv bin/micromamba ./micromamba
-
  matrix:
    only:
      - image: Ubuntu2204
  install:
    - wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1

build_script:
  - ./micromamba --version
  - ./micromamba shell init -s bash --root-prefix ~/micromamba
  - source ~/.bashrc
  - source ~/.profile
  - hash -r
  - mkdir -p ~/micromamba/pkgs/
  - mkdir -p ~/.mamba/pkgs/
  - export MAMBA_ROOT_PREFIX=~/micromamba
  - export MAMBA_EXE=$(pwd)/micromamba
  - . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
  - micromamba create -y -f environment.yml -c conda-forge
  - micromamba activate ~/micromamba/envs/agriculture-vlab
  - python3 setup.py install
  - python3 -m pytest
