name: agriculture-vlab
channels:
  - conda-forge
dependencies:
  - boto3 >=1.35.1
  - cartopy >=0.24.0
  - click >=8.1.0
  - matplotlib-base >=3.9.0
  - numpy >=1.17
  - pandas >=2.2.0
  - pyproj >=3.6.0
  - python >=3.11
  - tenacity >=9.0.0
  - xarray >=2024.9.0
  - xcube >=1.7.0
  - zarr >=2.17
  # Testing
  - pytest >=8.0.0
  - pytest-cov >=6.0.0
  - moto >=5
