name: agriculture-vlab
channels:
  - conda-forge
dependencies:
  - boto3 >=1.20.24
  - click >=8.0
  - numpy >=1.17
  - pandas >=1.3
  - pyproj  # use xcube's version constraints
  - xarray >=0.18.2
  - xcube >=0.10.1
  - zarr >=2.8
  # Testing
  - pytest >=4.4
  - pytest-cov >=2.6
  - moto >=3.0.5
