site_name: "Agriculture Virtual Lab"
site_url: "http://127.0.0.1:8000/"   # TODO!
copyright: Copyright (c) 2021 by the AVL Team
theme: readthedocs
# theme: mkdocs

nav:
  - Home: index.md
  - User Guide:
    - "Exploitation System: JupyterLab": guide/exploitation/jupyter.md
#    - "Exploitation System: Catalogue": guide/exploitation/catalogue.md
    - "Exploitation System: Viewer": guide/exploitation/viewer.md
    - Processing System Guide: guide/processing/index.md
    - CLI Tools: guide/tools.md
  - Python API Reference: mkapi/api/avl
  - Datasets:
    - Conventions: datasets/conventions.md
    - Altimetric datasets: datasets/altimetric.md
    - Atmospheric datasets: datasets/atmospheric.md
    - Optical datasets: datasets/optical.md
    - Passive microwave datasets: datasets/passive_microwave.md
    - Radar datasets: datasets/radar.md
    - Vector datasets: datasets/vector.md
    - Open datasets: datasets/open_datasets.md
    - xcube store datasets: datasets/xcube.md
  - Design:
    - Overview: design/index.md
    - Architecture and common components: design/common.md
    - Processing system design: design/processing/index.md
    - Exploitation system design: design/exploitation/index.md
    - Development: design/development.md
    - Software reuse: design/reuse.md
    - "Testing: Processing system": design/testing/processing.md
    - "Testing: Exploitation system": design/testing/exploitation.md
  - About:
    - Project: about/index.md
    - License: about/license.md

plugins:
  - search
  - mkapi

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - attr_list
